import Markdown from 'react-markdown';

export default function MarkdownComponent() {
	const markdown= '# Hello Markdown!\n## This is a component generated by markdown';

	return <><Markdown>{markdown}</Markdown></>;
}

